//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubManagementApp.Domain.Model
{
    public partial class User 
    {
        public System.Guid Id { get; set; } 
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Birthdate { get; set; }
        //public Licence Licence { get; set; }
        public short GenderId { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
